@startuml Debugger

package sprunk.extensions.debugger {
    class GameObjectDebugger {
        + GameObjectDebugger(HtmlElement: HTMLElement)
        + title(title: string): void
        + render(): void
    }
}

package "LilGUI" {
    class GUI
}

GameObjectDebugger *-- GUI

@enduml
