@startuml

package core {
    package behaviors {
        class Behavior
        class OutputBehavior
        class LogicBehavior
        class InputBehavior
    }

    class GameObject
    class GameEngineComponent
    class GameEngineWindow

    package tickers {
        class Ticker
        class FixedTimeTicker
        class AnimationFrameTimeTicker
    }

    package mathStructures {
        class Transform
        class Vector3
        class Vector2
        class Quaternion
        class MathUtility
    }

    package eventSystem {
        class Event
    }

    package extensions {
        class Sprunk
    }
}
package extensions.renderengine {
    class Renderer
    class RenderBehavior
    class Camera
    class RenderEngineUtility
    class SpriteRenderBehavior
    class BasicUVTexturedRenderBehavior
    class TextRenderBehavior
    class WireframeRenderBehavior
    class LinesRenderBehavior
    class Color
}

package extensions.debugger{
    class GameObjectDebugger
    class GUI
}

GameObject --> Transform
GameObject --> Behavior
GameObject --> GameEngineWindow
GameEngineComponent <|-- GameEngineWindow
GameEngineComponent --> GameEngineWindow

Ticker <|-- FixedTimeTicker
Ticker <|-- AnimationFrameTimeTicker

Transform --> Vector3
Transform --> Quaternion

Vector3 --> Vector2
Quaternion --> Vector3

Event <-- LogicBehavior
Event <-- Ticker

RenderGameEngineComponent -up-|> GameEngineComponent
RenderBehavior -up-|> OutputBehavior
SpriteRenderBehavior -up-|> BasicUVTexturedRenderBehavior
BasicUVTexturedRenderBehavior -up-|> RenderBehavior
TextRenderBehavior -up-|> RenderBehavior
WireframeRenderBehavior -up-|> RenderBehavior
LinesRenderBehavior -up-|> WireframeRenderBehavior

RenderGameEngineComponent --> Camera
RenderGameEngineComponent ..> RenderBehavior : "uses"
RenderBehavior ..> RenderEngineUtiliy : "uses"
Camera ..> RenderEngineUtiliy : "uses"
WireframeRenderBehavior ..> Color : "uses"
LinesRenderBehavior ..> Color : "uses"

@enduml
