@startuml 

package sprunk.extensions.audioengine {
    class OutputBehavior {
      // Base class for output behaviors
    }

    class AudioBehavior {
      + loop: boolean = false
      + constructor(audioContextFactory?: () => AudioContext)
      + reinitialize(): void
      + setAudio(audio: string): Promise<void>
      + play(audio: string | null): Promise<void>
      + pause(): Promise<void>
      + stop(): Promise<void>
      + setVolume(volume: number): void
      + setPitch(pitch: number): void
      + setLoop(loop: boolean): void
      + getTimestamp(): number
    }
}

AudioBehavior -up-|> OutputBehavior

@enduml