name: CI

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code with Git LFS support
      - name: Check out code with Git LFS
        uses: actions/checkout@v3
        with:
          lfs: true

      # Set CI environment variable for CI-specific config
      - name: Set CI environment variable
        run: echo "CI=true" >> $GITHUB_ENV

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Run Vitest
      - name: Run tests
        run: npm run test:ci

      # Output test results
      - name: Upload test results
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: ./test-results
  build:
    runs-on: ubuntu-latest
    needs: test

    steps:
      # Checkout the code with Git LFS support
      - name: Check out code with Git LFS
        uses: actions/checkout@v3
        with:
          lfs: true

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Build the project
      - name: Build project
        run: npm run build

  publish:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'  # Only run this job on the 'main' branch

    steps:
      # Checkout the code with Git LFS support
      - name: Check out code with Git LFS
        uses: actions/checkout@v3
        with:
          lfs: true

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Ensure the NPM_TOKEN is stored in the GitHub secrets
      - name: Check npm whoami
        run: npm whoami
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      # Publish as a beta release
      - name: Publish to npm as beta
        run: npm publish --tag beta
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}